---
name: Cupboard Listener
topic: events
brokerConnectionString: '192.168.1.11:29092,192.168.1.11:9092,192.168.1.11:9101'
isDatabase: false
interfaces:
  - name: Unused
    relay: 1
    pin_number: 18
    relay_on_activate: false
  - name: Unused
    relay: 2
    pin_number: 24
    relay_on_activate: false
  - name: Unused
    relay: 3
    pin_number: 23
    relay_on_activate: false
  - name: Unused
    relay: 4
    pin_number: 25
    relay_on_activate: false
  - name: Unused
    relay: 5
    pin_number: 21
    relay_on_activate: false
  - name: RightCupboard
    relay: 6
    pin_number: 13
    relay_on_activate: false
  - name: Unused
    relay: 7
    pin_number: 16
    relay_on_activate: false
  - name: LeftCupboard
    relay: 8
    pin_number: 26
    relay_on_activate: false
