name: Key Listener
topic: events
brokerConnectionString: '192.168.1.15:29092,192.168.1.15:9092,192.168.1.15:9101'
isDatabase: true
interfaces:
  - name: Key1
    relay: 1
    pin_number: 18
    relay_on_activate: false