---
name: Key Listener
brokerConnectionString: '192.168.1.11:29092,192.168.1.11:9092,192.168.1.11:9101'
topic: events
isDatabase: false
interfaces:
  - name: Key1
    relay: 1
    pin_number: 18
    relay_on_activate: false
  - name: Key2
    relay: 2
    pin_number: 24
    relay_on_activate: false
  - name: Key3
    relay: 3
    pin_number: 23
    relay_on_activate: false
  - name: Key4
    relay: 4
    pin_number: 25
    relay_on_activate: false
  - name: Key5
    relay: 5
    pin_number: 21
    relay_on_activate: false
  - name: Key6
    relay: 6
    pin_number: 20
    relay_on_activate: false
  - name: PipeLock
    relay: 7
    pin_number: 16
    relay_on_activate: true
  - name: LidLocks
    relay: 8
    pin_number: 12
    relay_on_activate: true
